* Who am I?
** Matt Hamrick
+ Software Programmer
+ Functional programmer
+ Emacs user
+ Millikin University graduate (Class of 2014)
+ Occasional Runner
+ Regular Guitar Player
+ Constant Reader

* Executive Overview
I'm a life-long learner who is deeply interested and invested in personal
development. I love working on and completing challenging problems. I'm
passionate about education, mentorship and enjoy teaching people new things. I
spend much of my free time learning new programming languages and seeing how
their novel concepts can improve previous work. I'm careful in ensuring that my
title, ego, age, gender or orientation don't interfere in finding the best
solution to a problem. To accomplish this, I make a habit of talking (and
listening) to others and making sure to acknowledge, improve, and eventually
fix, held biases. I work extremely hard, and do my best to accomplish the most I
can with the resources I'm provided.

* Work History
** June 2014 - Present
+ Since early 2017, I've been working in Research & Development. In this role,
  I've been able to research new technologies and find where their application
  can improve business processes. In order to showcase where improvements or
  innovations can be made, I've created small prototypes & MVPs show how the new
  work aligns with the current and future vision of the company.
+ From Late 2015 to early 2017, I worked on a Clojure business rule DSL. I spent
  a lot of time prototyping with exciting technologies. A few of note are:
  Spark, Scala, Zeppelin, Clojure and Clojurescript, Dynamic Soap Client
  Generation, EmberJs, React, Graph Computing, and Big Data. While working with
  these technologies, I was able to round out my full-stack skills. I also
  worked closely with business partners utilizing an iterate-and-demo approach.
  This helped me deeply understand their problems, and ensure that my solutions
  were as applicable as possible.
+ From 2014, to late 2015, I worked on the front-end of a Java Spring app that
  was delivered to production. On this project, I learned about mocking
  frameworks, different testing methodologies, Data-driven UIs, and Java
  reflection.

** 2013 Internship
+ During the summer of 2013, I worked as an intern at State Farm. While there, I
  worked on Spring, Java, and JavaScript technologies as a part of a
  modernization effort. I also participated in a speech program focusing on
  professional communication. The program culminated with an innovation project
  that focused on collaboration and out of the box thinking. My team's
  innovation idea made it to the final round and we presented the idea directly
  to executive Leadership.

* Technical Skills
+ Clojure/ClojureScript (10/10)
+ Java (9/10)
+ JavaScript (9/10)
+ Haskell (8/10)
+ Scheme (7/10)
+ Scala (6/10)
+ Python (6/10)

* Ask Me About
Functional Programming, Generative Testing, Systems Architecture, TDD, Immutable
Message Logs, SOLID Principles, Event-sourcing, Logic Programming, Type Systems,
Seven Languages in Seven Weeks, The Little Schemer, Peter (the cat)

* What have I done outside of Work?
+ [[https://diminishedprime.github.io/secret-agent-ui/][A Web-based Clone of a Board Game!]]
+ [[https://github.com/diminishedprime/anagrams][A Simple Clojure Library for finding Anagrams]]
+ [[./euler/index.org][Many Project Euler Questions]]
+ [[./reading-list/index.org][Technical Reading]]

* What do I Like?
+ Solving difficult problems
+ Teaching
+ Mentoring
+ Programming languages
+ Successful live demos
+ Playing Guitar
+ Peter (the Cat)
