[[../index.org][Main Index]]
[[../index.org][Reading List]]
[[../an_introduction_to_statistical_learning.org][Book]]

* Classification
** Lectures
   + [ ] [[https://www.youtube.com/playlist?list=PL5-da3qGB5IC4vaDba5ClatUmFppXLAhE][Playlist]]
     + [ ] [[https://www.youtube.com/watch?v=sqq21-VIa1c][Introduction to Classification]]
     + [ ] [[https://www.youtube.com/watch?v=31Q5FGRnxt4][Logistic Regression and Maximum Likelihood]]
     + [ ] [[https://www.youtube.com/watch?v=MpX8rVv_u4E][Multivariate Logistic Regression and Confounding]]
     + [ ] [[https://www.youtube.com/watch?v=GavRXXEHGqU][Case-Control Sampling and Multiclass Logistic Regression]]
     + [ ] [[https://www.youtube.com/watch?v=RfrGiG1Hm3M][Linear Discriminant Analysis and Bayes Theorem]]
     + [ ] [[https://www.youtube.com/watch?v=QG0pVJXT6EU][Univariate Linear Discriminant Analysis]]
     + [ ] [[https://www.youtube.com/watch?v=X4VDZDp2vqw][Multivariate Linear Discriminant Analysis and ROC Curves]]
     + [ ] [[https://www.youtube.com/watch?v=6FiNGTYAOAA][Quadratic Discriminant Analysis and Naive Bayes]]
     + [ ] [[https://www.youtube.com/watch?v=TxvEVc8YNlU][Lab: Logistic Regression]]
     + [ ] [[https://www.youtube.com/watch?v=2cl7JiPzkBY][Lab: Linear Discriminant Analysis]]
     + [ ] [[https://www.youtube.com/watch?v=9TVVF7CS3F4][Lab: K-Nearest Neighbors]]
** Reading List
1. [X] An Overview of Classification
2. [X] Why Not Linear Regression?
3. [X] Logistic Regression
4. [X] Linear Discriminant Analysis
5. [X] A Comparison of Classification Methods
6. [X] Lab: Logistic Regression, LDA, QDA, and KNN
7. [X] Exercises
   + [X] Conceptual
     1. [X] nah
     2. [X] also nah
     3. [X] Nah tho
     4. [X]
        + [X] (a) ~9.75%
        + [X] (b) ~9.75%^2 ~= 0.95%
        + [X] (c) ~9.75%^100 ~= 0%
        + [X] (d) the fraction of observations that will be used to make the
          prediction grows exponentially by the number of features. This
          means that there will be less and less observations that can be
          used.
        + [X] (e) apparently the =l = 0.1 for p=1=, =0.1^(1/2) for p=2= and
          =0.1^(1/n) for p=n=
     5. [X]
        + [X] (a) If the Bayes decision boundary is linear, we would expect the
          QDA to perform better on the training set since a higher flexibility
          tends to result in a better fit. However, the LDA should do better
          than QDA on the test set since the QDA would tend to overfit to the
          training set if the real value is linear.
        + [X] (b) If the Bayes decision boundary is non-linear, we would expect
          the QDA to perform bettor on both the training set and the test set
          due to its higher flexibility. Since the real model is not linear, the
          test data wouldn't be fit well by the model that LDA would make.
        + [X] (c) Generally speaking, QDA will do better if the traning set is
          very large since we don't have to have major concern about the
          variance of the classifier.
        + [X] (d) False, QDA has a higher variance which tends to lead to
          overfit on the test data. This leads to a worse test error rate than a
          lower variance method.
     6. [X]
        + [X] (a) =p(x)=e^(-6+0.05X1+X2)/(1+e^-6+0.05X1+X2)= = 0.3775
        + [X] (b) =p(x)=e^(-6+0.05X1+X2)/(1+e^-6+0.05X1+X2)0.5= solving the
          equation gives us =50 hours=
     7. [X] nah
     8. [X] Since 1-nearest neighbors has a training error rate of 0% and this
        problem reports the "average" error rate of 18%, there is a test error
        rate of 36% for KNN. We should choose logistic regression in this case
        since it only has 30% error on the test data.
     9. [X]
        + [X] (a) =p(X)/(1-p(X))=0.37= which can be transformed to =p(X)=0.37/(1+0.37)=0.27=
        + [X] (b) this one is a bit simplier since we can just plug it into the
          original formula. We get =0.16/(1-0.16)=0.19= for the odds
   + [X] Applied
     10. [@10] [X]
         + [X] (a) The only pattern seems to be that volume increases over time.
           #+BEGIN_SRC R
             library(ISLR)
             summary(Weekly)
           #+END_SRC
         + [X] (b) Technically, Lag 2 is statistically significant, but it's
           probably just random chance and not actually statistically
           significant.
           #+BEGIN_SRC R
             library(ISLR)
             attach(Weekly)
             fit.glm <- glm(Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume, data = Weekly, family=binomial)
             summary(fit.glm)
             cor(Weekly[, -9])
             plot(Volume, Year)
           #+END_SRC
         + [X] (c)
           #+BEGIN_SRC R
             library(ISLR)
             attach(Weekly)
             fit.glm <- glm(Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume, data = Weekly, family=binomial)
             probs <- predict(fit.glm, type = "response")
             ## Uses "rep" or "replicate" to create a vector that has "Down" the length of
             ## probs times.
             pred.glm <- rep("Down", length(probs))
             ## this changes the pred.glm Downs to Up if the matching prob index has a value
             ## of greater than 0.5
             pred.glm[probs > 0.5] <- "Up"
             table(pred.glm, Direction)
           #+END_SRC
           |----------+------+-----|
           | pred.glm | Down |  Up |
           |----------+------+-----|
           | Down     |   54 |  48 |
           | Up       |  430 | 557 |
           |----------+------+-----|
           The confusion matrix tells us that 54 of the predict downs actually
           went down and 557 of the predicted ups went up. In total the model is
           correct =(/ (+ 54 557) (+ 54 430 48 557.0))= => 0.56 of the time.
           This means that the training error rate is =(- 1 0.56)= => 0.44 of
           the time. We could also say that for weeks that the market went up,
           the model is right =(/ 557 (+ 557.0 48))= => 0.92 of the time.
           However, when the market actually went down, the model is only right
           =(/ 54 (+ 54 430.0))= => 0.11 of the time.
         + [X] (d)
           #+BEGIN_SRC R
             library(ISLR)
             attach(Weekly)
             train <- (Year < 2009)
             Weekly.20092010 <- Weekly[!train, ]
             Direction.20092010 <- Direction[!train]
             fit.glm <- glm(Direction ~ Lag2, data = Weekly, family = binomial, subset = train)
             summary(fit.glm)

             probs <- predict(fit.glm, Weekly.20092010, type="response")
             pred.glm <- rep("Down", length(probs))
             pred.glm[probs > 0.5] <- "Up"
             table(pred.glm, Direction.20092010)
           #+END_SRC
             |----------+------+----|
             | pred.glm | Down | Up |
             |----------+------+----|
             | Down     |    9 |  5 |
             | Up       |   34 | 56 |
             |----------+------+----|
         + [X] (e)
           #+BEGIN_SRC R
             library(ISLR)
             attach(Weekly)
             train <- (Year < 2009)
             Weekly.20092010 <- Weekly[!train, ]
             Direction.20092010 <- Direction[!train]
             fit.lda <- lda(Direction ~ Lag2, data = Weekly, subset = train)
             summary(fit.lda)

             probs <- predict(fit.lda, Weekly.20092010, type="response")
             pred.glm <- rep("Down", length(probs))
             pred.glm[probs > 0.5] <- "Up"
             table(pred.glm, Direction.20092010)
           #+END_SRC
             |----------+------+----|
             | pred.glm | Down | Up |
             |----------+------+----|
             | Down     |    9 |  5 |
             | Up       |   34 | 56 |
             |----------+------+----|
         + [X] (f)
           #+BEGIN_SRC R
             library(ISLR)
             attach(Weekly)
             train <- (Year < 2009)
             Weekly.20092010 <- Weekly[!train, ]
             Direction.20092010 <- Direction[!train]
             fit.qda <- qda(Direction ~ Lag2, data = Weekly, subset = train)
             summary(fit.qda)

             probs <- predict(fit.qda, Weekly.20092010, type="response")
             pred.glm <- rep("Down", length(probs))
             pred.glm[probs > 0.5] <- "Up"
             table(pred.glm, Direction.20092010)
           #+END_SRC
             |----------+------+----|
             | pred.glm | Down | Up |
             |----------+------+----|
             | Down     |    0 |  0 |
             | Up       |   43 | 61 |
             |----------+------+----|
         + [X] (g)
           #+BEGIN_SRC R
             library(ISLR)
             library(class)
             attach(Weekly)

             train <- (Year < 2009)
             train.X <- as.matrix(Lag2[train])
             test.X <- as.matrix(Lag2[!train])
             train.Direction <- Direction[train]
             set.seed(1)
             pred.knn <- knn(train.X, test.X, train.Direction, k = 1)
             table(pred.knn, Direction.20092010)
           #+END_SRC
             |----------+------+----|
             | pred.knn | Down | Up |
             |----------+------+----|
             | Down     |   21 | 30 |
             | Up       |   22 | 31 |
             |----------+------+----|
         + [X] (h) Comparing the error rates, lda & logistic regression have the
           best rates, followed by QDA and KNN
         + [X] (i) That sounds exhausting. How about no?
     11. [X]
         + [X] (a)
           #+BEGIN_SRC R
             library(ISLR)
             attach(Auto)

             mpg01 <- rep(0, length(mpg))
             mpg01[mpg > median(mpg)] <- 1
             Auto <- data.frame(Auto, mpg01)
           #+END_SRC
         + [X] (b)
           #+BEGIN_SRC R
             library(ISLR)
             attach(Auto)

             mpg01 <- rep(0, length(mpg))
             mpg01[mpg > median(mpg)] <- 1
             Auto <- data.frame(Auto, mpg01)
             cor(Auto[, -9])
             pairs(Auto)
           #+END_SRC
         + [X] (c)
           #+BEGIN_SRC R
             library(ISLR)
             attach(Auto)

             mpg01 <- rep(0, length(mpg))
             mpg01[mpg > median(mpg)] <- 1
             Auto <- data.frame(Auto, mpg01)

             train <- (year %% 2 == 0)
             Auto.train <- Auto[train, ]
             Auto.test <- Auto[!train, ]
             mpg01.test <- mpg01[!train]
           #+END_SRC
         + [X] (d) There is a test error of =0.1263736=
           #+BEGIN_SRC R
             library(ISLR)
             library(MASS)
             attach(Auto)

             mpg01 <- rep(0, length(mpg))
             mpg01[mpg > median(mpg)] <- 1
             Auto <- data.frame(Auto, mpg01)

             train <- (year %% 2 == 0)
             Auto.train <- Auto[train, ]
             Auto.test <- Auto[!train, ]
             mpg01.test <- mpg01[!train]

             fit.lda <- lda(mpg01 ~ cylinders + weight + displacement + horsepower, data = Auto, subset = train)
             fit.lda

             pred.lda <- predict(fit.lda, Auto.test)
             table(pred.lda$class, mpg01.test)
             mean(pred.lda$class != mpg01.test)
           #+END_SRC
         + [X] (e) There is a test error of =0.1318681=
           #+BEGIN_SRC R
             library(ISLR)
             library(MASS)
             attach(Auto)

             mpg01 <- rep(0, length(mpg))
             mpg01[mpg > median(mpg)] <- 1
             Auto <- data.frame(Auto, mpg01)

             train <- (year %% 2 == 0)
             Auto.train <- Auto[train, ]
             Auto.test <- Auto[!train, ]
             mpg01.test <- mpg01[!train]

             fit.qda <- qda(mpg01 ~ cylinders + weight + displacement + horsepower, data = Auto, subset = train)
             fit.qda

             pred.qda <- predict(fit.qda, Auto.test)
             table(pred.qda$class, mpg01.test)
             mean(pred.qda$class != mpg01.test)

           #+END_SRC
         + [X] (f) There is a test error of =0.1208791=
           #+BEGIN_SRC R
             library(ISLR)
             library(MASS)
             attach(Auto)

             mpg01 <- rep(0, length(mpg))
             mpg01[mpg > median(mpg)] <- 1
             Auto <- data.frame(Auto, mpg01)

             train <- (year %% 2 == 0)
             Auto.train <- Auto[train, ]
             Auto.test <- Auto[!train, ]
             mpg01.test <- mpg01[!train]

             fit.glm <- glm(mpg01 ~ cylinders + weight + displacement + horsepower, data = Auto, family = binomial, subset = train)
             summary(fit.glm)

             probs <- predict(fit.glm, Auto.test, type = "response")
             pred.glm <- rep(0, length(probs))
             pred.glm[probs > 0.5] <- 1
             table(pred.glm, mpg01.test)

             mean(pred.glm != mpg01.test)
           #+END_SRC
         + [X] (g) for k=1 there is an error rate of =0.1538462= for k=10 it is
           =0.1648352= and for k=100 it is =0.1428571=
           #+BEGIN_SRC R
             library(ISLR)
             library(class)
             library(MASS)
             attach(Auto)


             mpg01 <- rep(0, length(mpg))
             mpg01[mpg > median(mpg)] <- 1
             Auto <- data.frame(Auto, mpg01)

             train <- (year %% 2 == 0)
             train.X <- cbind(cylinders, weight, displacement, horsepower)[train, ]
             test.X <- cbind(cylinders, weight, displacement, horsepower)[!train, ]
             train.mpg01 <- mpg01[train]
             set.seed(1)

             pred.knn <- knn(train.X, test.X, train.mpg01, k = 1)
             table(pred.knn, mpg01.test)
             mean(pred.knn != mpg01.test)


             pred.knn <- knn(train.X, test.X, train.mpg01, k = 10)
             table(pred.knn, mpg01.test)
             mean(pred.knn != mpg01.test)

             pred.knn <- knn(train.X, test.X, train.mpg01, k = 100)
             table(pred.knn, mpg01.test)
             mean(pred.knn != mpg01.test)
           #+END_SRC
     12. [X]
         + [X] (a) =8=
           #+BEGIN_SRC R
             Power = function() {
                 print(2^3)
             }
             Power()
           #+END_SRC
         + [X] (b) =6561=
           #+BEGIN_SRC R
             Power2 = function(x, a) {
                 print(x^a)
             }
             Power2(3, 8)
           #+END_SRC
         + [X] (c) =1000= =2.2518e+15= =2248091=
           #+BEGIN_SRC R
             Power2 = function(x, a) {
                 print(x^a)
             }
             Power2(10 , 3)
             Power2(8  , 17)
             Power2(131, 3)
           #+END_SRC
         + [X] (d) =8=
           #+BEGIN_SRC R
             Power3 = function(x, a) {
                 result <- x ^ a
                 return(result)
             }
             Power3(2, 3)
           #+END_SRC
         + [X] (e)
           #+BEGIN_SRC R
             Power3 = function(x, a) {
                 result <- x ^ a
                 return(result)
             }

             x <- 1:10

             plot(x,
                  Power3(x, 2),
                  log = "xy",
                  xlab = "Log of x",
                  ylab = "Log of x^2",
                  main = "Log of x^2 vs Log of x")
           #+END_SRC
         + [X] (f)
           #+BEGIN_SRC R
             Power3 = function(x, a) {
                 result <- x ^ a
                 return(result)
             }

             PlotPower = function(r, power) {
                 p <- plot (r,
                            Power3(x, power),
                            log = "xy",
                            xlab = "Log of x",
                            ylab = "Log of x^2",
                            main = "Log of x^2 vs Log of x")
                 return(p)
             }
             PlotPower(1:10, 3)
           #+END_SRC
     13. [X]
         #+BEGIN_SRC R
           library(MASS)
           attach(Boston)
           crim01 <- rep(0, length(crim))
           crim01[crim > median(crim)] <- 1
           Boston <- data.frame(Boston, crim01)

           train <- 1:(length(crim) / 2)
           test <- (length(crim) / 2 + 1):length(crim)
           Boston.train <- Boston[train, ]
           Boston.test <- Boston[test, ]
           crim01.test <- crim01[test]

           fit.glm <- glm(crim01 ~ . - crim01 - crim, data = Boston, family = binomial, subset = train)

           probs <- predict(fit.glm, Boston.test, type = "response")
           pred.glm <- rep(0, length(probs))
           pred.glm[probs > 0.5] <- 1
           table(pred.glm, crim01.test)
           mean(pred.glm != crim01.test)
           ## 0.1818182


           fit.glm <- glm(crim01 ~ . - crim01 - crim - chas - nox, data = Boston, family = binomial, subset = train)
           probs <- predict(fit.glm, Boston.test, type = "response")
           pred.glm <- rep(0, length(probs))
           pred.glm[probs > 0.5] <- 1
           table(pred.glm, crim01.test)
           mean(pred.glm != crim01.test)
           ## 0.1581028


           fit.lda <- lda(crim01 ~ . - crim01 - crim, data = Boston, subset = train)
           pred.lda <- predict(fit.lda, Boston.test)
           table(pred.lda$class, crim01.test)
           mean(pred.lda$class != crim01.test)
           ## 0.1343874

           fit.lda <- lda(crim01 ~ . - crim01 - crim - chas - nox, data = Boston, subset = train)
           pred.lda <- predict(fit.lda, Boston.test)
           table(pred.lda$class, crim01.test)
           mean(pred.lda$class != crim01.test)
           ## 0.1501976

           train.X <- cbind(zn, indus, chas, nox, rm, age, dis, rad, tax, ptratio, black, lstat, medv)[train, ]
           test.X <- cbind(zn, indus, chas, nox, rm, age, dis, rad, tax, ptratio, black, lstat, medv)[test, ]
           train.crim01 <- crim01[train]
           set.seed(1)
           pred.knn <- knn(train.X, test.X, train.crim01, k = 1)
           table(pred.knn, crim01.test)
           mean(pred.knn != crim01.test)
           ## 0.458498

           pred.knn <- knn(train.X, test.X, train.crim01, k = 10)
           table(pred.knn, crim01.test)
           mean(pred.knn != crim01.test)
           ## 0.1185771

           pred.knn <- knn(train.X, test.X, train.crim01, k = 100)
           table(pred.knn, crim01.test)
           mean(pred.knn != crim01.test)
           ## 0.4901186
         #+END_SRC
