+ [[../index.org][Main Index]]
+ [[./index.org][Song Index]]

* Such Great Heights
** Iron and Wine
   Standard tuning, capo on 6th fret.

MAIN RIFF...
E|-------6----------------------9-------------9----------------------------------6----------9------|
G|--7----------7-----7-----6-----------6------------------6-----------6-----7----------9----------6|
B|----6-----6-----6-----6----6------6------6------6-------------6-------------6-----6----6------6--|
D|-----8-----8-----8-----8----6------6------6------6---6-----6-----6-----6-----8-----8----6------6-|
A|--9-----9-----9-----9----------6h8--------------------9-----9-----9-----9-9-----9----------6h8---|
E|--------------------------9------------9------9----7-----7-----7-----7---------------6-----------|

High-pitched thing at the end but maybe down a few octaves...
E|--6-7-6---6-9-11-9---9-7-7-6---6-6-7-6---9-9-6-6-|
G|--7-----7---9------9---7-----7---7-----7-9-----7-|
B|--6---------6----------8---------6-------6-----6-|
D|--8---------6----------9---------8-------6-----8-|
A|--9---------8----------9---------9-------8-----9-|
E|------------9----------7-----------------9-------|

The first riff composes pretty much the whole song, with some hammer ons added to the
second and last chord shapes.
Lyrics, for added convenience, are as follows, and are organized per riff(So for
each line written, you play the riff once.) You should be able
to pick up the tempo fairly quickly, it's pretty straightforward.

--
(Riff x2)

I'm thinking it's a sign that the freckles in our eyes are mirror images and when
we kiss they're perfectly aligned
and I have to speculate that god himself did make us into corresponding shapes like
puzzle pieces from the clay
and true, it may seeem like a stretch, but it's thoughts like this that catch my
troubled head when you're away when I am missing you to death
when you're there on the road for several weeks of shows and when you scan the
radio I hope this song will guide you home

(CHORUS)
They will see us waving from such great heights, come down now, they'll say
but everything looks perfect from far away, come down now, but we'll stay

I try my best to leave this all on your machine but the persistent beat it
sounded thin upon listening
and that frankly will not fly, you will hear the shrillest highs and lowest
lows with the windows down when this is guiding you home

(CHORUS)
they will see us waving from such great heights, come down now they'll say
but everything looks perfect from far away, come down now, but we'll stay

(Riff x1 as everything fades out. I've more or less transcribed the mandolin part if you
like playing that, but I won't really call it an outro or whatever.)
--

Great song. Very soft, very mellow.
I think my tab's fairly accurate, please rate away. When I feel even MORE proactive I'll
it up relative to the capo.
